edc.participant.id=consumer

web.http.port=39191
web.http.path=/api
web.http.management.path=/api/management
web.http.management.port=39193

edc.catalog.cache.execution.delay.seconds=5
edc.catalog.cache.execution.period.seconds=5
edc.catalog.cache.partition.num.crawlers=1
