name: First Interaction

on:
  issues:
    types: [ opened ]
  pull_request_target:
    types: [ opened ]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thanks for your contribution :fire: We will take a look asap :rocket:'
          pr-message: >-
            'We are always happy to welcome new contributors :heart: To make things easier for everyone, please
            - make sure to follow our [contribution guidelines](https://github.com/eclipse-edc/Samples/blob/main/CONTRIBUTING.md),
            - check if you have already signed the [ECA](http://www.eclipse.org/legal/ecafaq.php), and
            - relate this pull request to an existing issue or discussion.'