name: First Interaction

on:
  issues:
    types: [ opened ]
  pull_request_target:
    types: [ opened ]

jobs:
  trigger-workflow:
    uses: eclipse-edc/.github/.github/workflows/first-interaction.yml@main
    secrets:
      envGH: ${{ secrets.GITHUB_TOKEN }}
